IQSD-1228: Форма запроса персональных данных для анонимных клиентов
iqstore/iqchannels-widget pull request #45
Opened 2024-06-29 17:06 UTC by aakoroleva

https://jira.iqstore.ru/browse/IQSD-1228

2024-06-30 13:48 UTC, Pavelavl commented
в info-request.vue у класса pending убрать padding 10px, переименовать .div в какой нибудь inner и вынести inline-стиль туда и добавить ему padding 10px, а то форма плывет чут чут

![image](https://github.com/iqstore/iqchannels-widget/assets/62856796/630548bc-6daf-4be3-9ad6-3cc2d5929524)

2024-06-30 14:00 UTC, Pavelavl requested changes

2024-06-30 14:00 UTC, Pavelavl commented on src/app/messenger/info-request.vue
> +    .button
оставить .buttons

2024-06-30 14:00 UTC, Pavelavl commented on src/app/messenger/info-request.vue
> +    console.log({d: this.client});
log

2024-06-30 14:00 UTC, Pavelavl commented on src/client/index.js
> +    this.sending = null;
тут другие indents стояли? весь файл почему-то светится

2024-07-01 06:57 UTC, aakoroleva commented on src/client/index.js
> +    this.sending = null;
да, у тебя как будто на два пробела настроено

2024-07-01 07:06 UTC, Pavelavl approved these changes

2024-07-01 07:06 UTC, merged