draft IQSD-1931
iqstore/iqchannels-widget pull request #46
Opened 2024-07-03 22:28 UTC by aakoroleva

https://jira.iqstore.ru/browse/IQSD-1931

2024-07-16 22:22 UTC, Pavelavl requested changes
Модалка не открывается (ПКМ по сообщению)
![image](https://github.com/user-attachments/assets/c4e8d263-88e4-410d-9c4b-4c3f97b3631e)

хз было или нет, но баг такой еще
![image](https://github.com/user-attachments/assets/ebc809df-d64c-4c33-85a2-48c47e9e3fca)

затерлись некоторые стили
пример со стенда:
![image](https://github.com/user-attachments/assets/8850d2a2-c721-4812-9f9d-8e2983a1627c)
с коммита:
![image](https://github.com/user-attachments/assets/c4139e39-6759-49c3-aeed-d21d080728f5)

Тож потерялся стиль, когда нету сообщений
![image](https://github.com/user-attachments/assets/88652a4c-1931-43ca-8e9f-a4cf050e79b1)



Мб что то еще, опасна

В целом я бы создал новую ветку от мастера и черрипикнул туда основные изменения с коммитов

2024-07-17 07:19 UTC, aakoroleva commented
некоторые стили убраны/добавлены специально

изменения и так черри-пикнуты, это не особо решает проблемы, потому что chat разбился на несколько компонентов, в итоге все равно перенос руками

основное пофиксила, если что -- пиши, буду поправлять приоритетно

2024-07-17 09:48 UTC, Pavelavl commented
А зачем этот стиль затирать? кнопка шире становится, не круглая :\
.csm-btn {
margin-left: 5px;
height: 35px;
min-width: 35px;
}

2024-07-17 09:50 UTC, Pavelavl commented
![image](https://github.com/user-attachments/assets/c1e0d4be-2c96-4e92-9009-1cd8414f54f3)
![image](https://github.com/user-attachments/assets/ca0334f5-309b-4367-81ee-09260dea9f86)

С тем же стендом если сравнивать, кнопки меньше места на стенде занимают

2024-07-17 10:41 UTC, Pavelavl requested changes
![image](https://github.com/user-attachments/assets/31b85e62-90ef-4925-88d2-6f0f5d6206ec)

Поиск тож не работает, потерялся стиль cursor: pointer и обработчика нету

2024-07-17 10:41 UTC, Pavelavl commented on src/app/messenger/message/message.vue
> +    },
enableImgModals потерялся

2024-07-17 15:25 UTC, aakoroleva commented
кнопки немного изменила все-таки, оставим до замечаний с тестирования

2024-07-17 21:26 UTC, merged